# Generated by Django 6.0.1 on 2026-01-11 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackChannelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.CharField(max_length=32, unique=True)),
                ("channel_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Slack Channel Configuration",
                "verbose_name_plural": "Slack Channel Configurations",
                "db_table": "slack_channel_configs",
            },
        ),
        migrations.CreateModel(
            name="SlackMessageCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("message_count", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="slack_analytics.slackchannelconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Message Count",
                "verbose_name_plural": "Slack Message Counts",
                "db_table": "slack_message_counts",
                "unique_together": {("channel", "date")},
            },
        ),
    ]
